accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"
# 127.0.0.1:8000/account/hello_world/ -> accountapp:hello_world(name)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

koterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [

    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView


app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>

    {% block content %}

    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <div class="koterest_footer">
        <div class="koterest_footer_button">
            <span>공지사항</span> |
            <span>버그문의</span> |
            <span>서비스소개</span>
        </div>
        <div>
            <h5 class="koterest_footer_logo">Koterest</h5>
        </div>
    </div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Koterest</title>

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gugi&display=swap" rel="stylesheet">

    {#  GOOGLE MATERIAL ICONS  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

</head>

templates/header.html
    <div class="koterest_header">
        <div>
            <a href="{% url 'articleapp:list' %}" class="text-dark text-decoration-none ">
                <h1 class="koterest_header_logo">Koterest</h1>
            </a>
        </div>
        <div class="koterest_header_navbar">
            <a href="{% url 'articleapp:list' %}" class="koterest_header_nav text-dark text-decoration-none ">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="koterest_header_nav text-dark text-decoration-none">
                <span>Projects</span>
            </a>
            {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next{{ request.path }}" class="koterest_header_nav text-dark text-decoration-none">
                    <span>login</span>
                </a>
                <a href="{% url 'accountapp:create' %}" class="koterest_header_nav text-dark text-decoration-none">
                    <span>Signup</span>
                </a>
            {% else %}
                <a href="{% url 'subscribeapp:list' %}" class="koterest_header_nav text-dark text-decoration-none">
                    <span>Subscription</span>
                </a>
                <a href="{% url 'accountapp:detail' pk=user.pk %}" class="koterest_header_nav text-dark text-decoration-none">
                    <span>MyPage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next{{ request.path }}" class="koterest_header_nav text-dark text-decoration-none">
                    <span>Logout</span>
                </a>
            {% endif %}
        </div>
    </div>